"""The subtitle-preparation prompt the user hands to an AI before importing.

Kept as a template with fill-ins rather than one person's vocabulary, so it
works for a medical tutorial, a product demo or a lecture alike. The user's own
brand and terms go in the two placeholders and nowhere else.

The rules here exist because of what this app does downstream: narration is
generated per *sentence group*, not per subtitle, so the single most valuable
thing an editor can do is punctuate honestly — a full stop only where a sentence
truly ends. That is what lets the grouper find natural breaks instead of cutting
mid-phrase.
"""

from __future__ import annotations

BRAND_PLACEHOLDER = "[YOUR BRAND OR PRODUCT NAME]"
TERMS_PLACEHOLDER = "[list your specialist terms here, comma separated]"

SRT_PROMPT_TEMPLATE = """\
You are my subtitle editor. I will upload an SRT generated by Whisper or another
speech-to-text system. Prepare it for a timestamp-aware text-to-speech pipeline.

The result must be accurate, grammatically correct, natural when spoken, and
EXACTLY timestamp-preserved.

==================================================
1. TIMESTAMPS ARE SACRED
==================================================

NEVER change:
- subtitle number
- start timestamp
- end timestamp
- subtitle count
- overall duration

Do not merge, delete, reorder or retime subtitles.
Do not change timings to make the grammar work.

ONLY EDIT THE TEXT.

==================================================
2. SOURCE OF TRUTH
==================================================

The SRT comes from my actual recording.

Do NOT invent information, add facts I did not say, or remove content.
Do NOT substantially rewrite my meaning or reorder my points.
Your job is to polish what I actually said.

==================================================
3. TRANSCRIPTION ERRORS
==================================================

Correct obvious speech-to-text errors using the surrounding subtitles for
context: misheard words, accidental duplication, missing small words, wrong
capitalisation, punctuation, and clearly wrong terminology or names.

If a correction is uncertain, do NOT confidently invent one. Keep the closest
meaning the text supports.

==================================================
4. NAMES AND TERMINOLOGY
==================================================

Always write my brand exactly as:

{brand}

Correct obvious mis-hearings of it.

Pay particular attention to these specialist terms, checking context carefully:

{terms}

Do not change numbers, dates, doses, measurements, versions, scores or other
values unless the source text clearly supports the correction.

==================================================
5. NATURAL SPOKEN FLOW  (the most important section)
==================================================

Subtitle boundaries frequently fall in the MIDDLE of a sentence.

Do NOT treat each subtitle as a standalone sentence.
Do NOT add a full stop merely because a subtitle ends.

Read each subtitle together with the one before and after it, and make the text
flow continuously across the boundary.

GOOD:
  1: "Welcome to Acme, a platform built specifically for"
  2: "small teams and independent studios."

BAD:
  1: "Welcome to Acme, a platform built specifically for."
  2: "Small teams and independent studios."

==================================================
6. PUNCTUATION FOR SPEECH
==================================================

Punctuation tells the speech engine where to breathe.

- Commas where a short natural pause belongs.
- Full stops ONLY where a sentence genuinely ends.
- Keep a spoken list as one flowing list; do not break it into fragments.
- Where the recording genuinely changes topic, a real sentence boundary is
  correct and wanted.

The goal is natural narration, not one giant sentence.

==================================================
7. STYLE
==================================================

Preserve my voice: clear, confident, conversational, explaining something to a
peer. Not a research paper, and not marketing copy. Avoid added adjectives and
corporate phrasing. Remove accidental stammered repetition, but keep deliberate
emphasis.

==================================================
8. VERIFY BEFORE RETURNING
==================================================

Check that:
- subtitle count is unchanged
- every subtitle number is unchanged
- every start and end timestamp is unchanged, character for character
- the overall duration is unchanged

Then read the whole thing as one continuous script and ask: if the subtitle
boundaries vanished and a narrator read this aloud, would it sound natural?
If not, improve the TEXT — never the timestamps.

==================================================
9. OUTPUT
==================================================

Return:
1. The enhanced file as a downloadable .srt, named <original_name>_enhanced.srt
2. A short summary of the important corrections you made
3. The confirmation line:
   "All original timestamps and subtitle numbering have been preserved."
"""


def build_prompt(brand: str = "", terms: str = "") -> str:
    """Fill the template. Empty fields keep the visible placeholders."""
    return SRT_PROMPT_TEMPLATE.format(
        brand=brand.strip() or BRAND_PLACEHOLDER,
        terms=terms.strip() or TERMS_PLACEHOLDER,
    )


#: The workflow shown on the Home screen, before a file is ever imported.
WORKFLOW_STEPS: tuple[tuple[str, str, str], ...] = (
    (
        "1",
        "Record your video, with your own voice on it",
        "Speak the script normally. The recording is only used to get an accurate "
        "transcript with timings — this app replaces the voice afterwards.",
    ),
    (
        "2",
        "Ask ChatGPT for a subtitle file (.srt)",
        "Upload your video to ChatGPT and ask it to generate an .srt subtitle file "
        "with timings.",
    ),
    (
        "3",
        "Clean up the subtitle text in ChatGPT",
        "Speech-to-text mis-hears names and punctuates badly, which is what makes "
        "narration sound wrong. Paste the prompt below with your .srt — it fixes "
        "the wording while keeping every timestamp identical.",
    ),
    (
        "4",
        "Bring the .srt here",
        "Drop it in above. Choose a voice, generate, listen to the whole thing, "
        "then export the audio for your editor.",
    ),
)
